apiVersion: v2
name: matrix-agent-manager
description: Open-source control plane for managing Matrix-based agents
type: application
version: 0.1.8
appVersion: 0.1.8
home: https://github.com/ksamaschke/matrix-agent-manager
sources:
  - https://github.com/ksamaschke/matrix-agent-manager
keywords:
  - matrix
  - agents
  - kubernetes
  - oidc
  - mas
maintainers: []

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/ksamaschke/matrix-agent-manager
