apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrix-agent-manager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matrix-agent-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
